### ISSUE TITLE
[Checklist] Data protection suggestions

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1435]
Checklist to track suggested issues to improve how we manage data

**Short Term**
- [ ] Stop passing auth information from firebase into the main IDEMS database (only pass auth_id for linking) 
- [ ] Add system (or just document how) to enable people to access auth information from firebase on request

**Medium Term**
- [ ] Add methods so that any user-input data is encrypted on the device and in our database

**Longer-Term**
- [ ] Explore options to remove the need for firebase, managing an authentication system on our own servers instead, e.g. [Parse Platform](https://parseplatform.org/)
