### ISSUE TITLE
[CHECKLIST] Theme system ongoing changes

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1468]
Just to track issues emerging from ongoing PRs and discussions

Follwing #1439 
- [ ] deprecate unused variables (as per regex suggestions )
- [ ] clarify any additional calcs required (e.g. light/lighter/lightest vs 50 - 900 weight system), following the point flagged  for the tile buttons
- [ ] figure out gradients
- [ ] refactor legacy calcs to use defined pallet instead
- [ ] test with another deployment to see how the theming looks
- [ ] start adding support for fonts, spacing etc.
- [ ] fix up or deprecate theme service depending on what we want to do with it

Follwing #1466
- [ ] deprecate tertiary colour (replace with fixed gradients or fixed colour variables, e.g. --color-yellow or --gradient-yellow)
- [ ] consider system for exposing and overriding specific variables
- [ ] integrate override into authoring
