### ISSUE TITLE
[Checklist] App Data Parsing

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1492]
Following #1482

- [ ] Parser integration
- [ ] replace instances of `evaluateJSExpression` with new jsEvaluator class
- [ ] consider replacing templateVariablesService methods with newer classes where possible
- [ ] consider moving all shared methods to new package (e.g. app-templating)
- [ ] consider tidying up naming of models, e.g. making models all `contextModels` that extend a common base with setContext and evaluate/parse methods
- [ ] decide how best to handle runtime evaluation (e.g. what to do if fields context not provided)
- [ ] add documentation
- [x] add normalize function to ensure all columns added to datalist in json with incomplete values
- [ ] integrate normlize function to all existing methods

Additional

- [ ] Add better support/handling for 'id' column - use as [index on dataframes](https://danfo.jsdata.org/api-reference/dataframe/dataframe.set_index) (where exists) for operations like concat and merge. Allow override as required.
