### ISSUE TITLE
[Checklist] Server API Improvements

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1928]
**Details**
Following #1893 

- [ ] Consider refactoring all endpoints to extend a common base to reduce boilerplate code
- [ ] Update documentation to include how to write to different DBs
- [ ] Create E2E infrastructure to allow testing of db methods
- [ ] Add tests for core use-cases
- [ ] Update docker file to include local yarn cache for faster installs (similar to some github actions)
- [ ] Review current yarn/lock implementation and see if cleaner way to allow immutable install

Note - There are some additional short-term code updates/fixes on the main server itself which should also be resolved (namely certs renewal volume issue and use of ts-node/register in production
