### ISSUE TITLE
[Checklist] Git Repos Improvements

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1958]
Potential areas for future development identified in #1755

**Core Functionality**
- [ ] Fix CI integrations

**Code Tidying**
- [ ] Add outputs for deployment create/import and use for set

**CI**
- [ ] Add example actions for standalone deployment (web preview, android release)
- [ ] Add scripts and templates to make it easier to automatically populate deployment repo actions
- [ ] Add actions to automatically open PRs

**Content**
- [ ] PR to remove app-data (once fully deprecated), should also change default app_data.output_path
- [ ] Populate PLH content repo
- [ ] Remove hardcode app_data paths from config

**Repo**
- [ ] Remove historic large file history and lfs files
- [ ] Handle line endings (gitattributes?)
- [ ] Ensure git-lfs installed

**Scripts**
- [ ] Possibly refactor script as a provider (e.g. custom provider)
- [ ] Move all workflows to scripts (?)… unlikely to include custom
- [ ] Rename tasks to providers
- [ ] Publish external app scripts package and include in repo with package.json to allow triggering from content repo
- [ ] Migrate additional code to ts-morph (e.g. template file)

**Git**
- [ ] Scripts to populate a specific content version/track stable/preview etc. pipelines or branches
- [ ] Add support for target app version from content repo and include in build

**Misc**
- [ ] Update release system for core app
- [ ] Consider an extension system to manage additional deployment settings, e.g. android folder containing splash/icon for generating android assets or capacitor settings (populated on deployment change)
- [ ] Better feedback on long operations, such as git repo sync for large repo

**Comment by chrismclarke** [comment]
It's been a while since writing this list, I'd say around half the items have been implemented, a handful likely no longer required and then ideally the rest should be converted to standalone issues.
