### ISSUE TITLE
[Checklist] ODK Form Improvements

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#1964]
**Details**
Follow-ups from #1926 

**Test Cases**
- [ ] Image attachments
- [ ] Image inputs
- [ ] Form value preload/edit
- [ ] Form validation
- [ ] Multiple choice from file
- [ ] Supported widgets (decide what should/shouldn't be included in implementation)

**Additional**
- [ ] Documentation
- [ ] JSON output
- [ ] Dynamic form updates (e.g. populating based on fields and data lists)
- [ ] Handle 
- [ ] Data saving strategy (e.g. autosave all changes vs user click save form button)
- [ ] Review dependencies (node-forge not included, possibly some others required for widgets e.g. leaflet-draw)
- [ ] Review translation options
- [ ] XLSForm auto conversion (e.g. when syncing assets, would require way to identify and new api endpoint)
