### ISSUE TITLE
Confirm routing changes with content team

### ISSUE THREAD

**Issue by chrismclarke** [IDEMSInternational/parenting-app-ui#253]
Following #247

## TODO
- [x] check content team are happy with the proposed changes to URL structures and happy to update existing flows</s>
- [ ] check scripts still identify invalid routes in task actions
- [ ] create an issue to automate process for checking valid routes in conversations parser (exit links)
- [ ] update chat service to support relative routes in spreadsheets (e.g. defined as `tips/my_tips` in the sheet, and retaining the same path during conversation parser for an app build, but appending web URL for rapidpro build (as mentioned in #216))

**Comment by michaelclapham** [comment]
Closing as chat no longer being used
